version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/usr/share/nginx/html:ro 
    depends_on:
      - product_service
      - order_service
      - notification_service
      - user_service

  product_service:
    build:
      context: ./product_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001" # REST
      - "50051:50051" # gRPC
    restart: on-failure
    
  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002" # REST
      - "50052:50052" # gRPC
    restart: on-failure

  notification_service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003" # REST
      - "50053:50053" # gRPC
    restart: on-failure

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
        - "5004:5004" # REST
        - "50054:50054" # gRPC